INSERT INTO
  `User` (`username`, `password`, `firstname`, `lastname`)
VALUES
  ("ipsum.", 2, "Kenneth", "Clayton"),
  ("mauris", 2, "Jameson", "Bass"),
  ("risus.", 1, "Bethany", "Heath"),
  ("aliquet", 1, "Steven", "Benjamin"),
  ("Integer", 2, "Derek", "Fischer"),
  ("elit", 2, "Chelsea", "Vega"),
  ("a", 1, "Solomon", "Juarez"),
  ("Donec", 1, "Caesar", "Cooley"),
  ("dolor,", 2, "Jacob", "Buchanan"),
  ("Maecenas", 2, "Marshall", "Sherman");

INSERT INTO
  `Manufacturer` (`mfrname`)
VALUES
  ("Acura"),
  ("Alfa Romeo"),
  ("Aston Martin"),
  ("Audi"),
  ("Bentley"),
  ("BMW"),
  ("Buick"),
  ("Cadillac"),
  ("Chevrolet"),
  ("Chrysler"),
  ("Dodge"),
  ("Ferrari"),
  ("FIAT"),
  ("Ford Freightliner Genesis"),
  ("GMC"),
  ("Honda"),
  ("Hyundai"),
  ("INFINITI"),
  ("Jaguar"),
  ("Jeep"),
  ("Kia"),
  ("Lamborghini"),
  ("Land Rover"),
  ("Lexus"),
  ("Lincoln"),
  ("Lotus"),
  ("Maserati"),
  ("MAZDA"),
  ("McLaren"),
  ("Mercedes-Benz"),
  ("MINI"),
  ("Mitsubishi"),
  ("Nissan"),
  ("Porsche"),
  ("Ram"),
  ("Rolls-Royce"),
  ("SAAB"),
  ("smart"),
  ("Subaru"),
  ("Tesla"),
  ("Toyota"),
  ("Vauxhall"),
  ("Volkswagen"),
  ("Volvo");

